# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
formats:
  - htmlzip
  - pdf
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: idmlaser
      extra_requirements:
        - test
search:
  ranking:
    installation.html: 3
    idmlaser.html: 2
