# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/conf.py
  # TODO: Re-enable `fail_on_warning` once the namespace migration is complete and all Sphinx warnings are resolved.
  #       See tracking issue: https://github.com/your-org/your-repo/issues/1234
  fail_on_warning: false

formats:
  - htmlzip
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - test

search:
  ranking:
    installation.html: 3
    laser_core.html: 2
