site_name: LASER
site_url: https://mizzo-idm.github.io/laser/
repo_name: MIzzo-IDM/laser
repo_url: https://github.com/MIzzo-IDM/laser
theme:
  name: material
  custom_dir: customization/overrides
  font: 
    text: Roboto
    code: Roboto Mono
  logo: images/idm-logo-transparent.png
  favicon: images/favicon.ico
  features:
    - navigation.footer
    - content.code.copy

  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: light blue

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: white
      accent: light blue

nav:
  - Home: index.md
  - What's new: whatsnew.md
  - Installation: installation.md
  - Software overview:
    - software-overview/index.md
    - Components:
      - software-overview/components/index.md
      - software-overview/components/demographics.md
      - software-overview/components/migration.md
      - software-overview/components/database.md
    - software-overview/modules.md
  - Get tarted modeling:
    - get-started/index.md
    - get-started/custom.md
    - get-started/initialization.md
    - get-started/complexity.md
    - get-started/calibration.md
    - get-started/optimization.md
  - Tutorials:
    - tutorials/index.md
    - tutorials/sir.md
    - tutorials/squashing-sir.md
    - tutorials/age_pyramid.ipynb
    - tutorials/kmestimator.ipynb
  - Parameters: parameters.md # place holder for API docs
  - Glossary: glossary.md
  - Development: development.md

watch:
  - customization/includes # for the abbreviations file

# icons, semantic markup, emojis 
markdown_extensions:
  - toc:
      toc_depth: 3
  - abbr
  - attr_list # enables HTMl and CSS classes to inline elements
  - md_in_html # enables grids
  - admonition # warnings, etc.
  - def_list
  - footnotes
  - pymdownx.emoji: # emojis and icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex: # Latex processing
      generic: true
  - pymdownx.snippets: # glossary and snippet reuse
     # auto_append: customization/includes/glossary.md #hitting permissionerror
  - pymdownx.blocks.details: # allows nesting of collapsible code

# markdown formatting
  - pymdownx.highlight: # syntax highlighting for code blocks
      linenums: true
      default_lang: 'python'
  - pymdownx.inlinehilite # syntax highlighting for inline code
  - pymdownx.superfences # enables code, diagram fences to be nested in lists, etc.
  - pymdownx.details # collapsible elements
  - pymdownx.tabbed: # tabbed content that can be toggled
      alternate_style: true
  - pymdownx.blocks.caption # captions for images, tables, etc.

# javascript customization
extra_javascript:
  - customization/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
  - search
  - autorefs # automatically create linkable references
  - include-markdown: # include other files, such as READMEs
  - mkdocs-jupyter:
      execute: false
      allow_errors: true
      include-source: true
  - section-index # enables nested sections
  - table-reader

copyright: Copyright &copy; 2025 Gates Foundation. All rights reserved.

extra:
  generator: false
  footer_links:
    - text: "Privacy and Cookies Notice"
    - href: "https://www.gatesfoundation.org/Privacy-and-Cookies-Notice"
    - text: "Terms of Use"
    - href: "https://www.gatesfoundation.org/Terms-of-Use"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/InstituteforDiseaseModeling/modeling-hub
    - icon: fontawesome/regular/envelope
      link: mailto:idm@gatesfoundation.org
    - icon: octicons/globe-24
      link: https://idmod.org
    - icon: simple/youtube
      link: http://www.youtube.com/@institutefordiseasemodelin1987
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/institute-disease-modeling

  analytics:
  provider: google
  property: G-SVDSQH04EM
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/emoticon-happy-outline
        name: This page was helpful
        data: 1
        note: >-
          Thanks for your feedback! If you like, provide additional information by
          using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
      - icon: material/emoticon-sad-outline
        name: This page could be improved
        data: 0
        note: >-
          Thanks for your feedback! Help us improve this page by
          using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
