iso_codes_mosaic = [
     "AGO", "BEN", "BWA", "BFA", "BDI", "CMR", "CAF", "TCD",
     "COG", "COD", "CIV", "GNQ", "ERI", "SWZ", "ETH", "GAB", "GMB",
     "GHA", "GIN", "GNB", "KEN", "LSO", "LBR", "MWI", "MLI", "MRT",
     "MOZ", "NAM", "NER", "NGA", "RWA", "SEN", "SLE",
     "SOM", "ZAF", "SSD", "TGO", "UGA", "TZA", "ZMB", "ZWE"
]

sorted_by_pop = [
    "NGA",
    "ETH",
    "COD",
    "ZAF",
    "TZA",
    "KEN",
    "UGA",
    "SDN",
    "GHA",
    "MOZ",
    "CIV",
    "CMR",
    "AGO",
    "NER",
    "BFA",
    "MWI",
    "SEN",
    "MLI",
    "ZMB",
    "ZWE",
    "RWA",
    "TCD",
    "GIN",
    "SOM",
    "BDI",
    "BEN",
    "SSD",
    "TGO",
    "SLE",
    "ERI",
    "CAF",
    "LBR",
    "COG",
    "MRT",
    "LSO",
    "NAM",
    "BWA",
    "GMB",
    "GNB",
    "GAB",
    "SWZ",
    "GNQ"
]
