site_name: LASER
theme:
  name: material

nav:
  - Home: readme.md
  - Installation: installation.md
  - Usage: usage.md
  - Architecture: architecture.md
  - Migration: migration.md
  - Pyramids: pyramids.md
  - KM Estimator: kmestimator.md
  - Example: example.md
  - VD Example: vdexample.md
  - Spatial Example: spatialexample.md
  - EULA: eula.md
  - Performance: performance.md
  - Calibration: calibration.md
  - Contributing: contributing.md
  - Authors: authors.md
  - Changelog: changelog.md

plugins:
  - search
  - pdf-export:
      verbose: true
